### ISSUE TITLE
Running on NixOS fails.

### ISSUE THREAD

**Issue by GalladeR475** [deltaphc/raylib-rs#144]
**ISSUE**
    Running `cargo run` on a raylib-rs project errors while installing glfw, curl and cmake on NixOS.
**ERROR**
    error: failed to run custom build command for `raylib-sys v3.7.0`

Caused by:
  process didn't exit successfully: `/home/USER/Documents/trackter/target/debug/build/raylib-sys-99612b4e7597fe84/build-script-build` (exit status: 101)
  --- stdout
  CMAKE_TOOLCHAIN_FILE_x86_64-unknown-linux-gnu = None
  CMAKE_TOOLCHAIN_FILE_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_TOOLCHAIN_FILE = None
  CMAKE_TOOLCHAIN_FILE = None
  CMAKE_GENERATOR_x86_64-unknown-linux-gnu = None
  CMAKE_GENERATOR_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  CMAKE_PREFIX_PATH_x86_64-unknown-linux-gnu = None
  CMAKE_PREFIX_PATH_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_x86_64-unknown-linux-gnu = None
  CMAKE_x86_64_unknown_linux_gnu = None
  HOST_CMAKE = None
  CMAKE = None
  running: "cmake" "/home/USER/Documents/trackter/target/debug/build/raylib-sys-b50135bb1e6abfc1/out/raylib" "-DBUILD_EXAMPLES=OFF" "-DCMAKE_BUILD_TYPE=Release" "-DSUPPORT_BUSY_WAIT_LOOP=OFF" "-DPLATFORM=Desktop" "-DCMAKE_INSTALL_PREFIX=/home/USER/Documents/trackter/target/debug/build/raylib-sys-b50135bb1e6abfc1/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/etc/profiles/per-user/USER/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/etc/profiles/per-user/rishabht/bin/c++" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_ASM_COMPILER=/etc/profiles/per-user/USER/bin/cc"
  -- Testing if -Werror=pointer-arith can be used -- compiles
  -- Testing if -Werror=implicit-function-declaration can be used -- compiles
  -- Testing if -fno-strict-aliasing can be used -- compiles
  -- Using raylib's GLFW
  -- Using X11 for window creation
  -- Configuring incomplete, errors occurred!
  See also "/home/USER/Documents/trackter/target/debug/build/raylib-sys-b50135bb1e6abfc1/out/build/CMakeFiles/CMakeOutput.log".

  --- stderr
  CMake Error at /nix/store/c5b6rbqxmvf447qvlswk6sxgl6cy1vky-cmake-3.22.3/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
    Could NOT find X11 (missing: X11_X11_INCLUDE_PATH X11_X11_LIB)
  Call Stack (most recent call first):
    /nix/store/c5b6rbqxmvf447qvlswk6sxgl6cy1vky-cmake-3.22.3/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
    /nix/store/c5b6rbqxmvf447qvlswk6sxgl6cy1vky-cmake-3.22.3/share/cmake-3.22/Modules/FindX11.cmake:457 (find_package_handle_standard_args)
    src/external/glfw/CMakeLists.txt:204 (find_package)

  thread 'main' panicked at '
  command did not execute successfully, got: exit status: 1

  build script failed, must exit now', /home/USER/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.49/src/lib.rs:1104:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by ChildishGiant** [comment]
Similar error on fedora 37
<details>
```
warning: unused manifest key: package.features
   Compiling raylib-sys v3.7.0
error: failed to run custom build command for `raylib-sys v3.7.0`

Caused by:
  process didn't exit successfully: `/run/media/als/hdd/code/games/raylib/rust/cards/target/debug/build/raylib-sys-99612b4e7597fe84/build-script-build` (exit status: 101)
  --- stdout
  CMAKE_TOOLCHAIN_FILE_x86_64-unknown-linux-gnu = None
  CMAKE_TOOLCHAIN_FILE_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_TOOLCHAIN_FILE = None
  CMAKE_TOOLCHAIN_FILE = None
  CMAKE_GENERATOR_x86_64-unknown-linux-gnu = None
  CMAKE_GENERATOR_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  CMAKE_PREFIX_PATH_x86_64-unknown-linux-gnu = None
  CMAKE_PREFIX_PATH_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_x86_64-unknown-linux-gnu = None
  CMAKE_x86_64_unknown_linux_gnu = None
  HOST_CMAKE = None
  CMAKE = None
  running: "cmake" "/run/media/als/hdd/code/games/raylib/rust/cards/target/debug/build/raylib-sys-b50135bb1e6abfc1/out/raylib" "-DBUILD_EXAMPLES=OFF" "-DCMAKE_BUILD_TYPE=Release" "-DSUPPORT_BUSY_WAIT_LOOP=OFF" "-DPLATFORM=Desktop" "-DCMAKE_INSTALL_PREFIX=/run/media/als/hdd/code/games/raylib/rust/cards/target/debug/build/raylib-sys-b50135bb1e6abfc1/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/lib64/ccache/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/lib64/ccache/c++" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_ASM_COMPILER=/usr/lib64/ccache/cc"
  -- Testing if -Werror=pointer-arith can be used -- compiles
  -- Testing if -Werror=implicit-function-declaration can be used -- compiles
  -- Testing if -fno-strict-aliasing can be used -- compiles
  -- Using raylib's GLFW
  -- Using X11 for window creation
  -- Configuring incomplete, errors occurred!
  See also "/run/media/als/hdd/code/games/raylib/rust/cards/target/debug/build/raylib-sys-b50135bb1e6abfc1/out/build/CMakeFiles/CMakeOutput.log".

  --- stderr
  CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
    Could NOT find X11 (missing: X11_X11_INCLUDE_PATH X11_X11_LIB)
  Call Stack (most recent call first):
    /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
    /usr/share/cmake/Modules/FindX11.cmake:481 (find_package_handle_standard_args)
    src/external/glfw/CMakeLists.txt:204 (find_package)


  thread 'main' panicked at '
  command did not execute successfully, got: exit status: 1

  build script failed, must exit now', /home/als/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.49/src/lib.rs:1104:5
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:575:5
     1: core::panicking::panic_fmt
               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:65:14
     2: cmake::fail
               at /home/als/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.49/src/lib.rs:1104:5
     3: cmake::run
               at /home/als/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.49/src/lib.rs:1082:9
     4: cmake::Config::build
               at /home/als/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.49/src/lib.rs:819:13
     5: build_script_build::build_with_cmake
               at ./build.rs:71:15
     6: build_script_build::main
               at ./build.rs:202:5
     7: core::ops::function::FnOnce::call_once
               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/ops/function.rs:251:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
</details>

**Comment by GalladeR475** [comment]
I somehow figured it out, but I had to compile again due to version mismatch i.e. OpenGL was 3.0 on my linux machine, so I had to re-compile it with a lower version of OpenGL

**Comment by boblehest** [comment]
My experience running this on NixOS: Adding dependencies or changing versions of OpenGL (via the raylib-sys feature flags `opengl_*`) did _not_ help for me. What did help was to pass `USE_EXTERNAL_GLFW=ON` when building raylib (by patching `raylib-sys/build.rs`, and also adding `println!("cargo:rustc-link-lib=glfw");` even if wayland is not enabled).
