### ISSUE TITLE
Can't compile on Windows with MSVC 2019

### ISSUE THREAD

**Issue by Memorix101** [deltaphc/raylib-rs#25]
Hey, compiling doesn't work on my setup.

raylib MSVC lib and dll are at C:\Users\memor\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\x86_64-pc-windows-msvc\lib

Did I forget something to setup?

![image](https://user-images.githubusercontent.com/1466920/65838685-0124ab00-e306-11e9-8530-9f90195a8f2d.png)

![image](https://user-images.githubusercontent.com/1466920/65838689-07b32280-e306-11e9-88af-9018b1e552ab.png)

Compiler crashes with:
`C:/Users/memor/.cargo/bin/cargo.exe build --color=always --all --all-targets
    Updating crates.io index
    Blocking waiting for file lock on the registry index
 Downloading crates ...
  Downloaded raylib-sys v0.9.2
    Blocking waiting for file lock on raylib-sys-0.9.2.crate
   Compiling raylib-sys v0.9.2
   Compiling raylib-sys v0.11.0 (https://github.com/deltaphc/raylib-rs#e8137560)
error: failed to run custom build command for `raylib-sys v0.11.0 (https://github.com/deltaphc/raylib-rs#e8137560)`
process didn't exit successfully: `C:\Users\memor\Desktop\rust_raylib_space_invaders\target\debug\build\raylib-sys-3bb58d0274d07477\build-script-build` (exit code: 101)
--- stdout
out: "C:\\Users\\memor\\Desktop\\rust_raylib_space_invaders\\target\\debug\\build\\raylib-sys-2ce9a53141825ca3\\out"
url: "https://codeload.github.com/raysan5/raylib/tar.gz/2.5.0"
running: "cmake" "C:\\Users\\memor\\Desktop\\rust_raylib_space_invaders\\target\\debug\\build\\raylib-sys-2ce9a53141825ca3\\out\\raylib-2.5.0" "-G" "Visual Studio 16 2019" "-Thost=x64" "-Ax64" "-DBUILD_EXAMPLES=OFF" "-DBUILD_GAMES=OFF" "-DCMAKE_BUILD_TYPE=Release" "-DSUPPORT_BUSY_WAIT_LOOP=OFF" "-DSTATIC=TRUE" "-DPLATFORM=Desktop" "-DCMAKE_INSTALL_PREFIX=C:\\Users\\memor\\Desktop\\rust_raylib_space_invaders\\target\\debug\\build\\raylib-sys-2ce9a53141825ca3\\out" "-DCMAKE_C_FLAGS= -nologo -MD -Brepro" "-DCMAKE_C_FLAGS_RELEASE= -nologo -MD -Brepro" "-DCMAKE_CXX_FLAGS= -nologo -MD -Brepro" "-DCMAKE_CXX_FLAGS_RELEASE= -nologo -MD -Brepro"

--- stderr
CMake Error: Could not create named generator Visual Studio 16 2019

Generators
  Unix Makefiles               = Generates standard UNIX makefiles.
  Ninja                        = Generates build.ninja files.
  CodeBlocks - Ninja           = Generates CodeBlocks project files.
  CodeBlocks - Unix Makefiles  = Generates CodeBlocks project files.
  CodeLite - Ninja             = Generates CodeLite project files.
  CodeLite - Unix Makefiles    = Generates CodeLite project files.
  Sublime Text 2 - Ninja       = Generates Sublime Text 2 project files.
  Sublime Text 2 - Unix Makefiles
                               = Generates Sublime Text 2 project files.
  Kate - Ninja                 = Generates Kate project files.
  Kate - Unix Makefiles        = Generates Kate project files.
  Eclipse CDT4 - Ninja         = Generates Eclipse CDT 4.0 project files.
  Eclipse CDT4 - Unix Makefiles= Generates Eclipse CDT 4.0 project files.

thread 'main' panicked at '
command did not execute successfully, got: exit code: 1

build script failed, must exit now', C:\Users\memor\.cargo\registry\src\github.com-1ecc6299db9ec823\cmake-0.1.42\src\lib.rs:861:5
stack backtrace:
   0: std::sys::windows::backtrace::set_frames
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\sys\windows\backtrace\mod.rs:94
   1: std::sys::windows::backtrace::unwind_backtrace
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\sys\windows\backtrace\mod.rs:81
   2: std::sys_common::backtrace::_print
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\sys_common\backtrace.rs:70
   3: std::sys_common::backtrace::print
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\sys_common\backtrace.rs:58
   4: std::panicking::default_hook::{{closure}}
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\panicking.rs:200
   5: std::panicking::default_hook
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\panicking.rs:215
   6: std::panicking::rust_panic_with_hook
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\panicking.rs:478
   7: std::panicking::continue_panic_fmt
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\panicking.rs:385
   8: std::panicking::begin_panic_fmt
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\panicking.rs:340
   9: cmake::fail
             at C:\Users\memor\.cargo\registry\src\github.com-1ecc6299db9ec823\cmake-0.1.42\src\lib.rs:861
  10: cmake::run
             at C:\Users\memor\.cargo\registry\src\github.com-1ecc6299db9ec823\cmake-0.1.42\src\lib.rs:839
  11: cmake::Config::build
             at C:\Users\memor\.cargo\registry\src\github.com-1ecc6299db9ec823\cmake-0.1.42\src\lib.rs:674
  12: build_script_build::build_with_cmake
             at .\build.rs:44
  13: build_script_build::main
             at .\build.rs:110
  14: std::rt::lang_start::{{closure}}<()>
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\src\libstd\rt.rs:64
  15: std::rt::lang_start_internal::{{closure}}
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\rt.rs:49
  16: std::panicking::try::do_call<closure,i32>
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\panicking.rs:297
  17: panic_unwind::__rust_maybe_catch_panic
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libpanic_unwind\lib.rs:92
  18: std::panicking::try
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\panicking.rs:276
  19: std::panic::catch_unwind
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\panic.rs:388
  20: std::rt::lang_start_internal
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\rt.rs:48
  21: std::rt::lang_start<()>
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\src\libstd\rt.rs:64
  22: main
  23: invoke_main
             at d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  24: __scrt_common_main_seh
             at d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  25: BaseThreadInitThunk
  26: RtlUserThreadStart

Process finished with exit code 101
`

**Comment by Memorix101** [comment]
`CMake Error: Could not create named generator Visual Studio 16 2019`
That is the problem here.

**Comment by Memorix101** [comment]
The issue was on my end. I've had two different versions of CMake in my system path. After removing the old one it worked out of the box.
