### ISSUE TITLE
sys build error on windows mingw64

### ISSUE THREAD

**Issue by omerakgoz34** [deltaphc/raylib-rs#67]
Windows 10 20H2
MinGW64 GCC v10.2.0 by MSYS2

<details>
<summary>Console log</summary>

```
cargo build
    Updating crates.io index
   Compiling cc v1.0.66
   Compiling fs_extra v1.2.0
   Compiling libc v0.2.80
   Compiling lazy_static v1.4.0
   Compiling cmake v0.1.45
   Compiling raylib-sys v3.0.0
error: failed to run custom build command for `raylib-sys v3.0.0`

Caused by:
  process didn't exit successfully: `C:\Users\omerakgoz34\Documents\Rust\raylib-deneme\target\debug\build\raylib-sys-804735ce89c4d091\build-script-build` (exit code: 101)
  --- stdout
  running: "cmake" "C:\\Users\\omerakgoz34\\Documents\\Rust\\raylib-deneme\\target\\debug\\build\\raylib-sys-c255182c0da0f4ab\\out\\raylib" "-G" "MinGW Makefiles" "-DBUILD_EXAMPLES=OFF" "-DBUILD_GAMES=OFF" "-DCMAKE_BUILD_TYPE=Release" "-DSUPPORT_BUSY_WAIT_LOOP=OFF" "-DSTATIC=TRUE" "-DPLATFORM=Desktop" "-DCMAKE_INSTALL_PREFIX=C:\\Users\\omerakgoz34\\Documents\\Rust\\raylib-deneme\\target\\debug\\build\\raylib-sys-c255182c0da0f4ab\\out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -m64" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -m64" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -m64"
  -- The C compiler identification is GNU 10.2.0
  -- The CXX compiler identification is GNU 10.2.0
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: C:/Users/omerakgoz34/scoop/apps/msys2/current/mingw64/bin/gcc.exe - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: C:/Users/omerakgoz34/scoop/apps/msys2/current/mingw64/bin/g++.exe - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Performing Test COMPILER_HAS_THOSE_TOGGLES
  -- Performing Test COMPILER_HAS_THOSE_TOGGLES - Success
  -- Testing if -Werror=pointer-arith can be used -- compiles
  -- Testing if -Werror=implicit-function-declaration can be used -- compiles
  -- Testing if -fno-strict-aliasing can be used -- compiles
  -- Testing if file system supports symlinks
  -- Testing if file system supports symlinks -- supported
  -- Using raylib's GLFW
  -- Looking for pthread.h
  -- Looking for pthread.h - found
  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
  -- Found Threads: TRUE
  -- Looking for dinput.h
  -- Looking for dinput.h - found
  -- Looking for xinput.h
  -- Looking for xinput.h - found
  -- Performing Test _GLFW_HAS_DEP
  -- Performing Test _GLFW_HAS_DEP - Success
  -- Performing Test _GLFW_HAS_ASLR
  -- Performing Test _GLFW_HAS_ASLR - Success
  -- Performing Test _GLFW_HAS_64ASLR
  -- Performing Test _GLFW_HAS_64ASLR - Success
  -- Using Win32 for window creation
  -- Audio Backend: miniaudio
  -- Building raylib static library
  -- Generated build type: Release
  -- Compiling with the flags:
  --   PLATFORM=PLATFORM_DESKTOP
  --   GRAPHICS=GRAPHICS_API_OPENGL_33
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/omerakgoz34/Documents/Rust/raylib-deneme/target/debug/build/raylib-sys-c255182c0da0f4ab/out/build
  running: "cmake" "--build" "." "--target" "install" "--config" "Debug" "--"
  Scanning dependencies of target glfw_objlib
  [  4%] Building C object src/external/glfw/src/CMakeFiles/glfw_objlib.dir/context.c.obj
  [  8%] Building C object src/external/glfw/src/CMakeFiles/glfw_objlib.dir/init.c.obj
  [ 12%] Building C object src/external/glfw/src/CMakeFiles/glfw_objlib.dir/input.c.obj
  [ 16%] Building C object src/external/glfw/src/CMakeFiles/glfw_objlib.dir/monitor.c.obj
  [ 20%] Building C object src/external/glfw/src/CMakeFiles/glfw_objlib.dir/vulkan.c.obj
  [ 25%] Building C object src/external/glfw/src/CMakeFiles/glfw_objlib.dir/window.c.obj
  [ 29%] Building C object src/external/glfw/src/CMakeFiles/glfw_objlib.dir/win32_init.c.obj
  [ 33%] Building C object src/external/glfw/src/CMakeFiles/glfw_objlib.dir/win32_joystick.c.obj
  [ 37%] Building C object src/external/glfw/src/CMakeFiles/glfw_objlib.dir/win32_monitor.c.obj
  [ 41%] Building C object src/external/glfw/src/CMakeFiles/glfw_objlib.dir/win32_time.c.obj
  [ 45%] Building C object src/external/glfw/src/CMakeFiles/glfw_objlib.dir/win32_thread.c.obj
  [ 50%] Building C object src/external/glfw/src/CMakeFiles/glfw_objlib.dir/win32_window.c.obj
  [ 54%] Building C object src/external/glfw/src/CMakeFiles/glfw_objlib.dir/wgl_context.c.obj
  [ 58%] Building C object src/external/glfw/src/CMakeFiles/glfw_objlib.dir/egl_context.c.obj
  [ 62%] Building C object src/external/glfw/src/CMakeFiles/glfw_objlib.dir/osmesa_context.c.obj
  [ 62%] Built target glfw_objlib
  Scanning dependencies of target glfw
  [ 66%] Linking C static library libglfw3.a
  [ 66%] Built target glfw
  Scanning dependencies of target raylib_static
  [ 75%] Building C object src/CMakeFiles/raylib_static.dir/core.c.obj
  [ 75%] Building C object src/CMakeFiles/raylib_static.dir/models.c.obj
  [ 79%] Building C object src/CMakeFiles/raylib_static.dir/raudio.c.obj
  [ 83%] Building C object src/CMakeFiles/raylib_static.dir/shapes.c.obj
  [ 87%] Building C object src/CMakeFiles/raylib_static.dir/text.c.obj
  [ 91%] Building C object src/CMakeFiles/raylib_static.dir/textures.c.obj
  [ 95%] Building C object src/CMakeFiles/raylib_static.dir/utils.c.obj
  [100%] Linking C static library libraylib_static.a
  [100%] Built target raylib_static
  Install the project...
  -- Install configuration: "Release"
  -- Installing: C:/Users/omerakgoz34/Documents/Rust/raylib-deneme/target/debug/build/raylib-sys-c255182c0da0f4ab/out/lib/libraylib_static.a
  -- Installing: C:/Users/omerakgoz34/Documents/Rust/raylib-deneme/target/debug/build/raylib-sys-c255182c0da0f4ab/out/include/raylib.h
  -- Installing: C:/Users/omerakgoz34/Documents/Rust/raylib-deneme/target/debug/build/raylib-sys-c255182c0da0f4ab/out/lib/pkgconfig/raylib.pc
  -- Installing: C:/Users/omerakgoz34/Documents/Rust/raylib-deneme/target/debug/build/raylib-sys-c255182c0da0f4ab/out/lib/cmake/raylib/raylib-config-version.cmake
  -- Installing: C:/Users/omerakgoz34/Documents/Rust/raylib-deneme/target/debug/build/raylib-sys-c255182c0da0f4ab/out/lib/cmake/raylib/raylib-config.cmake
  cargo:root=C:\Users\omerakgoz34\Documents\Rust\raylib-deneme\target\debug\build\raylib-sys-c255182c0da0f4ab\out

  --- stderr
  CMake Warning (dev) in CMakeLists.txt:
    No project() command is present.  The top-level CMakeLists.txt file must
    contain a literal, direct call to the project() command.  Add a line of
    code such as

      project(ProjectName)

    near the top of the file, but after cmake_minimum_required().

    CMake is pretending there is a "project(Project)" command on the first
    line.
  This warning is for project developers.  Use -Wno-dev to suppress it.

  CMake Warning:
    Manually-specified variables were not used by the project:

      CMAKE_ASM_FLAGS


  In file included from C:\Users\omerakgoz34\Documents\Rust\raylib-deneme\target\debug\build\raylib-sys-c255182c0da0f4ab\out\raylib\src\raudio.c:197:
  C:\Users\omerakgoz34\Documents\Rust\raylib-deneme\target\debug\build\raylib-sys-c255182c0da0f4ab\out\raylib\src\external/jar_mod.h: In function 'jar_mod_load':
  C:\Users\omerakgoz34\Documents\Rust\raylib-deneme\target\debug\build\raylib-sys-c255182c0da0f4ab\out\raylib\src\external/jar_mod.h:370:13: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
    370 |         d[i]=s[i];
        |         ~~~~^~~~~
  C:\Users\omerakgoz34\Documents\Rust\raylib-deneme\target\debug\build\raylib-sys-c255182c0da0f4ab\out\raylib\src\external/jar_mod.h:125:13: note: at offset 0 to object 'title' with size 20 declared here
    125 |     muchar  title[20];
        |             ^~~~~
  C:\Users\omerakgoz34\Documents\Rust\raylib-deneme\target\debug\build\raylib-sys-c255182c0da0f4ab\out\raylib\src\external/jar_mod.h:370:13: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
    370 |         d[i]=s[i];
        |         ~~~~^~~~~
  C:\Users\omerakgoz34\Documents\Rust\raylib-deneme\target\debug\build\raylib-sys-c255182c0da0f4ab\out\raylib\src\external/jar_mod.h:125:13: note: at offset 0 to object 'title' with size 20 declared here
    125 |     muchar  title[20];
        |             ^~~~~
  C:\Users\omerakgoz34\Documents\Rust\raylib-deneme\target\debug\build\raylib-sys-c255182c0da0f4ab\out\raylib\src\external/jar_mod.h:370:13: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
    370 |         d[i]=s[i];
        |         ~~~~^~~~~
  C:\Users\omerakgoz34\Documents\Rust\raylib-deneme\target\debug\build\raylib-sys-c255182c0da0f4ab\out\raylib\src\external/jar_mod.h:125:13: note: at offset 0 to object 'title' with size 20 declared here
    125 |     muchar  title[20];
        |             ^~~~~
  C:\Users\omerakgoz34\Documents\Rust\raylib-deneme\target\debug\build\raylib-sys-c255182c0da0f4ab\out\raylib\src\external/jar_mod.h:370:13: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
    370 |         d[i]=s[i];
        |         ~~~~^~~~~
  C:\Users\omerakgoz34\Documents\Rust\raylib-deneme\target\debug\build\raylib-sys-c255182c0da0f4ab\out\raylib\src\external/jar_mod.h:125:13: note: at offset 0 to object 'title' with size 20 declared here
    125 |     muchar  title[20];
        |             ^~~~~
  C:\Users\omerakgoz34\Documents\Rust\raylib-deneme\target\debug\build\raylib-sys-c255182c0da0f4ab\out\raylib\src\core.c: In function 'GetDirectoryPath':
  C:\Users\omerakgoz34\Documents\Rust\raylib-deneme\target\debug\build\raylib-sys-c255182c0da0f4ab\out\raylib\src\core.c:2028:9: warning: 'strncpy' specified bound depends on the length of the source argument [-Wstringop-overflow=]
   2028 |         strncpy(dirPath + ((filePath[1] != ':')? 2 : 0), filePath, strlen(filePath) - (strlen(lastSlash) - 1));
        |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  C:\Users\omerakgoz34\Documents\Rust\raylib-deneme\target\debug\build\raylib-sys-c255182c0da0f4ab\out\raylib\src\core.c:2028:68: note: length computed here
   2028 |         strncpy(dirPath + ((filePath[1] != ':')? 2 : 0), filePath, strlen(filePath) - (strlen(lastSlash) - 1));
        |                                                                    ^~~~~~~~~~~~~~~~
  In file included from C:\Users\omerakgoz34\Documents\Rust\raylib-deneme\target\debug\build\raylib-sys-c255182c0da0f4ab\out\raylib\src\textures.c:60:
  In function 'LoadImageEx',
      inlined from 'GenImageColor' at C:\Users\omerakgoz34\Documents\Rust\raylib-deneme\target\debug\build\raylib-sys-c255182c0da0f4ab\out\raylib\src\textures.c:2440:19,
      inlined from 'ImageTextEx' at C:\Users\omerakgoz34\Documents\Rust\raylib-deneme\target\debug\build\raylib-sys-c255182c0da0f4ab\out\raylib\src\textures.c:1940:20:
  C:\Users\omerakgoz34\Documents\Rust\raylib-deneme\target\debug\build\raylib-sys-c255182c0da0f4ab\out\raylib\src\raylib.h:106:33: warning: argument 1 range [18446744071562067968, 18446744073709551615] exceeds maximum object size 9223372036854775807 [-Walloc-size-larger-than=]
    106 |     #define RL_MALLOC(sz)       malloc(sz)
        |                                 ^~~~~~~~~~
  C:\Users\omerakgoz34\Documents\Rust\raylib-deneme\target\debug\build\raylib-sys-c255182c0da0f4ab\out\raylib\src\textures.c:321:35: note: in expansion of macro 'RL_MALLOC'
    321 |     image.data = (unsigned char *)RL_MALLOC(image.width*image.height*4*sizeof(unsigned char));
        |                                   ^~~~~~~~~
  In file included from C:\Users\omerakgoz34\Documents\Rust\raylib-deneme\target\debug\build\raylib-sys-c255182c0da0f4ab\out\raylib\src\textures.c:67:
  C:\Users\omerakgoz34\Documents\Rust\raylib-deneme\target\debug\build\raylib-sys-c255182c0da0f4ab\out\raylib\src\textures.c: In function 'ImageTextEx':
  C:/Users/omerakgoz34/scoop/apps/msys2/current/mingw64/x86_64-w64-mingw32/include/stdlib.h:531:17: note: in a call to allocation function 'malloc' declared here
    531 |   void *__cdecl malloc(size_t _Size);
        |                 ^~~~~~
  thread 'main' panicked at 'filed to create windows library: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }', C:\Users\omerakgoz34\.cargo\registry\src\github.com-1ecc6299db9ec823\raylib-sys-3.0.0\build.rs:81:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
</details>

**Comment by omerakgoz34** [comment]
NOT: I able to build raylib via cmake from the src folder.

**Comment by RayyanNafees** [comment]
How to build via CMAKE ?
Getting this error

```bash
❯ cargo run
   Compiling raylib-sys v5.0.2
error: failed to run custom build command for `raylib-sys v5.0.2`

Caused by:
  process didn't exit successfully: `F:\Etc\Rust\game\target\debug\build\raylib-sys-d6af56e502263c37\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-changed=build.rs
  cargo:rerun-if-changed=./binding/binding.h
  CMAKE_TOOLCHAIN_FILE_x86_64-pc-windows-gnu = None
  CMAKE_TOOLCHAIN_FILE_x86_64_pc_windows_gnu = None
  HOST_CMAKE_TOOLCHAIN_FILE = None
  CMAKE_TOOLCHAIN_FILE = None
  CMAKE_GENERATOR_x86_64-pc-windows-gnu = None
  CMAKE_GENERATOR_x86_64_pc_windows_gnu = None
  HOST_CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  CMAKE_PREFIX_PATH_x86_64-pc-windows-gnu = None
  CMAKE_PREFIX_PATH_x86_64_pc_windows_gnu = None
  HOST_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = Some("E:\\scoop\\apps\\raylib\\current;")
  CMAKE_x86_64-pc-windows-gnu = None
  CMAKE_x86_64_pc_windows_gnu = None
  HOST_CMAKE = None
  CMAKE = None
  running: "cmake" "F:\\Etc\\Rust\\game\\target\\debug\\build\\raylib-sys-c2e2ba0db9b91c92\\out\\raylib" "-G" "MSYS Makefiles" "-DCMAKE_BUILD_TYPE=Debug" "-DBUILD_EXAMPLES=OFF" "-DCMAKE_BUILD_TYPE=Debug" "-DSUPPORT_BUSY_WAIT_LOOP=OFF" "-DSUPPORT_FILEFORMAT_JPG=ON" "-DRAYMATH_STATIC_INLINE=ON" "-DUSE_WAYLAND=OFF" "-DOPENGL_VERSION=OFF" "-DSUPPORT_SCREEN_CAPTURE=ON" "-DSUPPORT_GIF_RECORDING=ON" "-DPLATFORM=Desktop" "-DCMAKE_INSTALL_PREFIX=F:\\Etc\\Rust\\game\\target\\debug\\build\\raylib-sys-c2e2ba0db9b91c92\\out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -m64" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -m64" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -m64"
  -- The C compiler identification is Clang 19.1.5 with GNU-like command-line
  -- The CXX compiler identification is Clang 19.1.5 with GNU-like command-line
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - failed
  -- Check for working C compiler: E:/scoop/apps/llvm/current/bin/clang.exe
  -- Check for working C compiler: E:/scoop/apps/llvm/current/bin/clang.exe - broken
  -- Configuring incomplete, errors occurred!

  --- stderr
  CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
    Compatibility with CMake < 3.10 will be removed from a future version of
    CMake.

    Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
    to tell CMake that the project requires at least <min> but has been updated
    to work with policies introduced by <max> or earlier.


  CMake Error at E:/scoop/apps/cmake/3.31.2/share/cmake-3.31/Modules/CMakeTestCCompiler.cmake:67 (message):
    The C compiler

      "E:/scoop/apps/llvm/current/bin/clang.exe"

    is not able to compile a simple test program.

    It fails with the following output:

      Change Dir: 'F:/Etc/Rust/game/target/debug/build/raylib-sys-c2e2ba0db9b91c92/out/build/CMakeFiles/CMakeScratch/TryCompile-fr6qaa'

      Run Build Command(s): E:/scoop/apps/cmake/3.31.2/bin/cmake.exe -E env VERBOSE=1 E:/scoop/shims/make.exe -f Makefile cmTC_b4cac/fast
      E:/scoop/apps/make/current/bin/make.exe  -f CMakeFiles/cmTC_b4cac.dir/build.make CMakeFiles/cmTC_b4cac.dir/build
      make[1]: Entering directory 'F:/Etc/Rust/game/target/debug/build/raylib-sys-c2e2ba0db9b91c92/out/build/CMakeFiles/CMakeScratch/TryCompile-fr6qaa'
      sh: /E/scoop/apps/cmake/3.31.2/bin/cmake.exe: not found
      make[1]: *** [CMakeFiles/cmTC_b4cac.dir/build.make:81: CMakeFiles/cmTC_b4cac.dir/testCCompiler.c.obj] Error 127
      make[1]: Leaving directory 'F:/Etc/Rust/game/target/debug/build/raylib-sys-c2e2ba0db9b91c92/out/build/CMakeFiles/CMakeScratch/TryCompile-fr6qaa'
      make: *** [Makefile:133: cmTC_b4cac/fast] Error 2





    CMake will not be able to correctly generate this project.
  Call Stack (most recent call first):
    CMakeLists.txt:2 (project)


  thread 'main' panicked at E:\scoop\persist\rustup-gnu\.cargo\registry\src\index.crates.io-6f17d22bba15001f\cmake-0.1.52\src/lib.rs:1115:5:

  command did not execute successfully, got: exit code: 1

  build script failed, must exit now
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  ```
